### PR TITLE
Digest stripped down

### PR DESCRIPTION
**Pull request by bago2k4**
Main PR: https://github.com/open-company/open-company-digest/pull/24

### CODE REVIEW

**Comment by bago2k4** [comment]
[Digest, stripped down](https://trello.com/c/EK17bO5d/2129-digest-stripped-down)

**Comment by belucid** [comment]
@bago2k4 in both Mail.app and Gmail app on mobile the "headers" ("MUST SEE", "NEW ACTIVITY", "FOLLOW UP") are nearly full left (tiny bit of padding/margin) but the design shows them alligned with the images (avatars and company logo). (FWIW looks fine on desktop)

**Comment by belucid** [comment]
@bago2k4 Too much space between explanation and link in footer: https://take.ms/ZKhQn

**Comment by bago2k4** [comment]
@belucid this should be good now.
### NB: I added a lib PR related to this but you might want to merge the [lib follow-up PR](https://github.com/open-company/open-company-lib/pull/68) since it's a child of it

**Pull request merged**
