### PR TITLE
Small GMail Improvements, Retina Sparklines

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/DI9neogR

This PR updates the generating of sparklines to 4x retina images. It also eliminates most cases of a p HTML tag as a direct subsequent sibling to a table HTML tag (which triggers a GMail specific rendering bug).

To test:

* Review the code
* Generate the snapshot email content below the `;; Generate test email HTML content from various snapshots` comment in the REPL comment section of `content.clj`. No errors? Retina images? Layout still good?
* Deploy to staging, send some emails. Retina images? Layout still good? All OK in gmail (except body following growth or finance metrics?)
* Merge
* Deploy to beta
* Go to your happy place

### CODE REVIEW

**Comment by bago2k4** [comment]
reviewing

**Comment by bago2k4** [comment]
@belucid couple of errors in sentry: https://sentry.io/opencompany/oc-staging-email/

**Comment by belucid** [comment]
@bago2k4 addressed by https://github.com/open-company/open-company-email/pull/6/commits/a0aa67efac29a6aa00f887d625e65de62420b15c

Already deployed to staging.

Ready.

**Comment by bago2k4** [comment]
reviewing again..

**Pull request merged**
